// =============================================
// PC MAX EDITION — Build data
// =============================================

const BUILD_DATA = {
  owner: "Максим",
  edition: "Custom Build · 2026 Q2",

  parts: [
    {
      id: "case",
      cat: "Корпус",
      name: "GameMax Spark Air",
      model: "BK · Mesh + Glass",
      price: 2119,
      qty: 1,
      color: "var(--text)",
      desc: "Mid-tower з mesh-передом для максимального airflow та загартованим склом збоку — щоб RGB не лишався без глядачів.",
      specs: [
        ["Форм-фактор",        "Micro-Tower · mATX / ITX"],
        ["Розміри",            "375 × 195 × 282 мм"],
        ["Макс. довжина GPU",  "350 мм"],
        ["Макс. висота кулера","168 мм"],
        ["Макс. довжина БЖ",   "220 мм"],
        ["Слоти SSD",          "4 × 2.5\""],
        ["Слоти HDD",          "1 × 3.5\""],
        ["Вентилятори",        "до 4 × 120 мм (front/rear/top/bottom)"],
        ["Бокова панель",      "Tempered Glass"],
        ["Передня панель",     "Mesh для максимального airflow"],
        ["Пилові фільтри",     "Знімні"],
      ],
      quickSpecs: [
        ["Форм-фактор",  "Micro-Tower · mATX / ITX"],
        ["Макс. GPU",    "350 мм"],
        ["Макс. кулер",  "168 мм"],
        ["Вентилятори",  "до 4 × 120 мм"],
        ["Слоти",        "4 × SSD · 1 × HDD"],
      ],
      icon: "case",
      photos: [
        "images/case/01.png", "images/case/02.png", "images/case/03.png",
        "images/case/04.png", "images/case/05.png", "images/case/06.png",
        "images/case/07.png", "images/case/08.png", "images/case/09.png",
        "images/case/10.png"
      ],
    },
    {
      id: "cpu",
      cat: "Процесор",
      name: "AMD Ryzen 5 5600",
      model: "Zen 3 · 6C/12T · sAM4",
      price: 5999,
      qty: 1,
      color: "var(--red)",
      desc: "6 ядер / 12 потоків Zen 3 — золота середина для 1080p гейму. Тримає високий FPS у CS2 і впевнено годує RTX 5060.",
      specs: [
        ["Ядра / Потоки",      "6 / 12"],
        ["Базова частота",     "3.5 GHz"],
        ["Boost частота",      "до 4.4 GHz"],
        ["Архітектура",        "Zen 3 (Vermeer)"],
        ["Техпроцес",          "TSMC 7nm FinFET"],
        ["L1 Cache",           "384 KB"],
        ["L2 Cache",           "3 MB"],
        ["L3 Cache",           "32 MB"],
        ["PCIe",               "4.0 · 24 лінії"],
        ["TDP / PPT",          "65W / 88W"],
        ["TDC / EDC",          "60A / 90A"],
        ["Сокет",              "AM4"],
        ["Пам'ять",            "DDR4 до 3200 MHz (офіц.)"],
      ],
      quickSpecs: [
        ["Ядра / Потоки",  "6 / 12"],
        ["Boost",          "до 4.4 GHz"],
        ["L3 Cache",       "32 MB"],
        ["Техпроцес",      "TSMC 7nm FinFET"],
        ["TDP / PPT",      "65W / 88W"],
      ],
      icon: "cpu",
      photos: ["images/cpu/01.png", "images/cpu/02.png"],
    },
    {
      id: "mobo",
      cat: "Материнська плата",
      name: "Gigabyte B550M Aorus Elite",
      model: "sAM4 · mATX · B550",
      price: 4499,
      qty: 1,
      color: "var(--green)",
      desc: "Надійна mATX-плата з PCIe 4.0, DDR4 до 4733 MHz та двома M.2-слотами. Підходить ідеально під 5600 + потенційний апгрейд.",
      specs: [
        ["Сокет / Чіпсет",    "AM4 · AMD B550"],
        ["Форм-фактор",       "Micro-ATX"],
        ["VRM",               "5+3 фаз Pure Digital"],
        ["RAM слоти",         "4 × DDR4 до 128 GB"],
        ["RAM частота",       "до 4733 MHz (OC)"],
        ["M.2 слоти",         "2 × M.2 (PCIe 4.0 + PCIe 3.0)"],
        ["PCIe x16",          "1 × PCIe 4.0 x16"],
        ["USB задня панель",  "4 × USB 3.2 + 4 × USB 2.0 + 1 × USB-C"],
        ["LAN",               "Realtek 8118 Gaming GbE"],
        ["Аудіо",             "Realtek ALC1200 7.1ch"],
        ["RGB / ARGB",        "1 × RGB + 1 × ARGB заголовок"],
        ["Fan Headers",       "1 × CPU + 4 × SYS PWM"],
        ["Q-Flash Plus",      "Оновлення BIOS без CPU/RAM"],
      ],
      quickSpecs: [
        ["Чіпсет",    "AMD B550 · AM4"],
        ["VRM",       "5+3 фаз Pure Digital"],
        ["M.2 слоти", "2 × (PCIe 4.0 + 3.0)"],
        ["LAN",       "Realtek 8118 Gaming GbE"],
        ["USB-C",     "1 × USB-C задня панель"],
      ],
      icon: "mobo",
      photos: [
        "images/mobo/01.png", "images/mobo/02.png", "images/mobo/03.png",
        "images/mobo/04.png", "images/mobo/05.png"
      ],
    },
    {
      id: "gpu",
      cat: "Відеокарта",
      name: "ASUS Dual RTX 5060",
      model: "8 GB GDDR7 · Dual",
      price: 18099,
      qty: 1,
      color: "var(--red)",
      desc: "RTX 5060 в компактному ASUS Dual виконанні — DLSS 4, Multi Frame Generation і повний ray tracing. Заточена під 1080p ultra без компромісів.",
      specs: [
        ["GPU",               "NVIDIA Blackwell · RTX 5060"],
        ["CUDA Cores",        "3840"],
        ["Tensor Cores",      "120 (5-го покоління)"],
        ["RT Cores",          "30 (4-го покоління)"],
        ["TMUs / ROPs",       "120 / 48"],
        ["VRAM",              "8 GB GDDR7 · 28 Gbps"],
        ["Шина пам'яті",      "128-bit"],
        ["Пропускна здатність","448 GB/s"],
        ["Base / Boost",      "2280 / 2497 MHz"],
        ["Інтерфейс",         "PCIe 5.0 x8"],
        ["TDP",               "145W · 1 × 8-pin"],
        ["Виходи",            "1 × HDMI 2.1b · 3 × DP 2.1b"],
        ["DLSS / Frame Gen",  "4.0 + Multi Frame Generation"],
      ],
      quickSpecs: [
        ["CUDA Cores",   "3840"],
        ["VRAM",         "8 GB GDDR7 · 448 GB/s"],
        ["Boost",        "2497 MHz"],
        ["DLSS",         "4.0 + Multi Frame Gen"],
        ["TDP",          "145W · PCIe 5.0 x8"],
      ],
      icon: "gpu",
      photos: [
        "images/gpu/01.png", "images/gpu/02.png",
        "images/gpu/03.png", "images/gpu/04.png"
      ],
    },
    {
      id: "ram",
      cat: "Оперативна пам'ять",
      name: "Kingston FURY Beast",
      model: "32 GB · DDR4-3200 · 2×16",
      price: 6700,
      qty: 1,
      color: "var(--cyan)",
      desc: "32 ГБ DDR4-3200 у двоканалі — більше ніж достатньо для будь-якої сучасної гри + важких вкладок Chrome у фоні.",
      specs: [
        ["Об'єм / Конфіг",    "32 GB · 2 × 16 GB · Dual-channel"],
        ["Тип",               "DDR4 UDIMM · 288-pin"],
        ["Частота (XMP)",     "3200 MHz"],
        ["Тайминги (XMP)",    "CL16-18-18-36"],
        ["Напруга (XMP)",     "1.35V"],
        ["Тайминги (JEDEC)",  "CL17-17-17-39"],
        ["Напруга (JEDEC)",   "1.2V @ 2400 MHz"],
        ["XMP профіль",       "Intel XMP 2.0 · AMD сумісність"],
        ["Радіатор",          "Low-profile heat spreader"],
        ["Гарантія",          "Довічна"],
      ],
      quickSpecs: [
        ["Об'єм",      "32 GB · 2×16 · Dual-ch."],
        ["Частота",    "3200 MHz (XMP)"],
        ["Тайминги",   "CL16-18-18-36"],
        ["Напруга",    "1.35V (XMP) / 1.2V (JEDEC)"],
        ["Гарантія",   "Довічна"],
      ],
      icon: "ram",
      photos: [
        "images/ram/01.png", "images/ram/02.png",
        "images/ram/03.png", "images/ram/04.png"
      ],
    },
    {
      id: "ssd1",
      cat: "SSD #1 — система",
      name: "Samsung PM981",
      model: "512 GB · NVMe M.2 · PCIe 3.0",
      price: 2700,
      qty: 1,
      color: "var(--violet)",
      desc: "Швидкий NVMe під систему та основні програми. Boot за 8 секунд, гра запускається ще до того, як встигнеш узяти миш.",
      specs: [
        ["Об'єм",             "512 GB"],
        ["Інтерфейс",         "PCIe 3.0 x4 NVMe 1.2"],
        ["Форм-фактор",       "M.2 2280 · однобічний"],
        ["NAND",              "Samsung 64-layer V-NAND TLC"],
        ["Контролер",         "Samsung Phoenix"],
        ["DRAM кеш",          "Є (LPDDR4)"],
        ["SEQ Read (Q8T1)",   "3394 MB/s · виміряно"],
        ["SEQ Write (Q8T1)",  "1988 MB/s · виміряно"],
        ["RND 4K Read",       "428 MB/s · виміряно"],
        ["RND 4K Write",      "296 MB/s · виміряно"],
        ["IOPS Read / Write", "до 380K / 440K"],
      ],
      quickSpecs: [
        ["SEQ Read",   "3394 MB/s · виміряно"],
        ["SEQ Write",  "1988 MB/s · виміряно"],
        ["NAND",       "Samsung V-NAND TLC 64L"],
        ["Кеш",        "LPDDR4 DRAM"],
        ["Інтерфейс",  "PCIe 3.0 x4 · M.2 2280"],
      ],
      icon: "ssd",
      photos: ["images/ssd1/01.png"],
    },
    {
      id: "ssd2",
      cat: "SSD #2 — ігри",
      name: "Kingston NV3 1TB",
      model: "M.2 NVMe · PCIe 4.0 x4",
      price: 3300,
      qty: 1,
      color: "var(--violet)",
      desc: "Терабайт PCIe 4.0 NVMe під ігрову бібліотеку. Cyberpunk, GOW, Forza — нехай ставляться всі одразу і завантажуються за секунди.",
      specs: [
        ["Об'єм",             "1 TB"],
        ["Інтерфейс",         "PCIe 4.0 x4 NVMe"],
        ["Форм-фактор",       "M.2 2280"],
        ["NAND",              "Kioxia BiCS6 162-layer 3D TLC/QLC"],
        ["Контролер",         "Silicon Motion SM2268XT2"],
        ["DRAM кеш",          "Без DRAM · HMB до 64 MB"],
        ["SEQ Read",          "до 6000 MB/s"],
        ["SEQ Write",         "до 4000 MB/s"],
        ["Витривалість TBW",  "320 TB"],
        ["MTBF",              "2 000 000 годин"],
      ],
      quickSpecs: [
        ["SEQ Read",   "до 6000 MB/s"],
        ["SEQ Write",  "до 4000 MB/s"],
        ["TBW",        "320 TB"],
        ["Кеш",        "Без DRAM · HMB 64 MB"],
        ["Інтерфейс",  "PCIe 4.0 x4 · M.2 2280"],
      ],
      icon: "ssd",
      photos: [
        "images/ssd2/01.png", "images/ssd2/02.png",
        "images/ssd2/03.png", "images/ssd2/04.png"
      ],
    },
    {
      id: "cooler",
      cat: "Кулер CPU",
      name: "ID-COOLING Frozn A410",
      model: "DK Black · Tower · 4 Heatpipes",
      price: 1099,
      qty: 1,
      color: "#d6d6e0",
      desc: "Tower-кулер з 4 тепловими трубками — тримає Ryzen 5 5600 холодним і тихим навіть на повному навантаженні.",
      specs: [
        ["Тип",               "Tower air · Single Tower"],
        ["Розміри",           "120 × 98 × 152 мм"],
        ["Вага",              "900 г (з вентиляторами)"],
        ["Теплові трубки",    "4 × 6 мм · Direct Touch"],
        ["Матеріал",          "Мідна основа · алюмінієві ребра"],
        ["Вентилятор",        "2 × 120 × 25 мм PWM"],
        ["Підшипник",         "Fluid Dynamic Bearing (FDB)"],
        ["RPM",               "500 ~ 2000 ± 10%"],
        ["Airflow",           "78.25 CFM (макс.)"],
        ["Статичний тиск",    "2.68 mmH₂O"],
        ["Шум",               "до 29.85 dB(A)"],
        ["Сумісність TDP",    "до 230W"],
        ["Сокети",            "AM4 / AM5 · LGA1700 / 1200 / 115x"],
      ],
      quickSpecs: [
        ["TDP",        "до 230W"],
        ["Heatpipes",  "4 × 6 мм · Direct Touch"],
        ["Шум",        "до 29.85 dB(A)"],
        ["Airflow",    "78.25 CFM"],
        ["Сокети",     "AM4 / AM5 / LGA1700"],
      ],
      icon: "cooler",
      photos: [
        "images/cooler/01.png", "images/cooler/02.png", "images/cooler/03.png",
        "images/cooler/04.png", "images/cooler/05.png", "images/cooler/06.png"
      ],
    },
    {
      id: "psu",
      cat: "Блок живлення",
      name: "MSI MAG A550BN",
      model: "550W · 80+ Bronze · Non-modular",
      price: 2599,
      qty: 1,
      color: "var(--amber)",
      desc: "550 ват сертифікації 80+ Bronze — стабільне живлення для RTX 5060 + Ryzen 5 з запасом.",
      specs: [
        ["Потужність",        "550W"],
        ["Сертифікація",      "80+ Bronze · до 85% ефективність"],
        ["Схемотехніка",      "DC-to-DC · Single Rail 12V"],
        ["Active PFC",        "Є"],
        ["Модульність",       "Non-modular"],
        ["Розміри",           "140 × 150 × 86 мм"],
        ["Вентилятор",        "120 мм FDB · Hong Hua"],
        ["Коннектори",        "1 × ATX 24-pin · 1 × CPU 4+4 · 2 × PCIe 6+2 · 6 × SATA · 3 × Molex"],
        ["Захисти",           "OCP · OVP · SCP · OTP · OPP"],
        ["Конденсатори",      "105°C rated · ChengX / CapXon"],
        ["Гарантія",          "5 років"],
      ],
      quickSpecs: [
        ["Потужність",  "550W · 80+ Bronze"],
        ["Схемотехніка","DC-to-DC · Single Rail 12V"],
        ["Вентилятор",  "120 мм FDB"],
        ["Захисти",     "OCP · OVP · SCP · OTP · OPP"],
        ["Гарантія",    "5 років"],
      ],
      icon: "psu",
      photos: [
        "images/psu/01.png", "images/psu/02.png", "images/psu/03.png",
        "images/psu/04.png", "images/psu/05.png", "images/psu/06.png",
        "images/psu/07.png", "images/psu/08.png"
      ],
    },
    {
      id: "fans",
      cat: "Вентилятори",
      name: "Arctic F12 PWM PST",
      model: "120 mm · ×2",
      price: 558,
      qty: 2,
      unitPrice: 279,
      color: "var(--cyan)",
      desc: "Тихі 120мм PWM-вертушки з PST для airflow всередині корпусу. Без зайвого шуму — просто роблять свою роботу.",
      specs: [
        ["Розмір",            "120 × 120 × 25 мм"],
        ["RPM",               "230 ~ 1350 PWM"],
        ["Airflow",           "53 CFM (91.1 м³/год)"],
        ["Статичний тиск",    "1.0 mmH₂O"],
        ["Шум",               "23.5 dB(A) · 0.3 Sone"],
        ["Підшипник",         "Fluid Dynamic Bearing (FDB)"],
        ["Конектор",          "4-pin PWM"],
        ["PST функція",       "PWM Sharing Technology · каскад"],
        ["Кількість",         "2 шт."],
        ["Гарантія",          "6 років"],
      ],
      quickSpecs: [
        ["Airflow",    "53 CFM (91.1 м³/год)"],
        ["Шум",        "23.5 dB(A) · 0.3 Sone"],
        ["RPM",        "230 ~ 1350 PWM"],
        ["PST",        "Каскадне підключення"],
        ["Гарантія",   "6 років"],
      ],
      icon: "fan",
      photos: [
        "images/fan/01.png", "images/fan/02.png", "images/fan/03.png"
      ],
    },
    {
      id: "tim",
      cat: "Термоінтерфейс",
      name: "Honeywell PTM7950",
      model: "Phase-change · 8.5 W/mK",
      price: 345,
      qty: 1,
      color: "var(--violet)",
      desc: "PTM7950 — термопрокладка з фазовим переходом, що рве звичайну пасту. Поставив один раз і забув.",
      specs: [
        ["Теплопровідність",  "8.5 W/m·K"],
        ["Тип",               "Phase-change pad"],
        ["Фазовий перехід",   "45°C (тверде → в'язке)"],
        ["Розмір",            "40 × 40 × 0.2 мм"],
        ["Термічний опір",    "0.04 °C·cm²/W"],
        ["Макс. температура", "150°C"],
        ["Питома вага",       "2.8 г/см³"],
        ["Нанесення",         "Готова прокладка · без розмазування"],
        ["Довговічність",     "~10 років · без pump-out ефекту"],
        ["Надійність",        "1000 термоциклів без деградації"],
      ],
      quickSpecs: [
        ["Теплопровідність", "8.5 W/m·K"],
        ["Фазовий перехід",  "45°C"],
        ["Термічний опір",   "0.04 °C·cm²/W"],
        ["Тип",              "Phase-change pad"],
        ["Довговічність",    "~10 років"],
      ],
      icon: "tim",
      photos: ["images/tim/01.png"],
    },
  ],

  // FPS in 1080p — RTX 5060 + R5 5600.
  // Заміри БЕЗ ліміту кадрів. Рекомендований ліміт для монітора — 144–180 FPS.
  // slug   — назва папки скрінів налаштувань: images/settings/<slug>/01.png, 02.png ...
  // shots  — скільки скрінів у папці (стільки й підтягнеться в галерею).
  // tCpu / tGpu — температури під час гри (°C), null = ще не заміряно (покаже прочерк).
  fpsNote: "Оптимальна картинка × кадри. Ліміт кадрів рекомендуємо ставити на 144–180 FPS — під частоту монітора, щоб відеокарта відпочивала.",
  fps: [
    { name: "Counter-Strike 2",        slug: "cs2",          shots: 3, avg: 320, lo: 220, tCpu: null, tGpu: null, cyan: true },
    { name: "Cyberpunk 2077",          slug: "cyberpunk",    shots: 3, avg: 95,  lo: 78,  tCpu: null, tGpu: null },
    { name: "God of War",     slug: "gow",          shots: 3, avg: 110, lo: 88,  tCpu: null, tGpu: null },
    { name: "Marvel's Spider-Man",     slug: "spiderman",    shots: 3, avg: 120, lo: 95,  tCpu: null, tGpu: null },
    { name: "Expedition 33",           slug: "expedition33", shots: 3, avg: 90,  lo: 72,  tCpu: null, tGpu: null },
    { name: "Forza Horizon 6",         slug: "forza",        shots: 3, avg: 130, lo: 102, tCpu: null, tGpu: null },
    { name: "Need for Speed Unbound",  slug: "nfs",          shots: 3, avg: 142, lo: 110, tCpu: null, tGpu: null },
  ],

  // Benchmark results
  benchmarks: [
    {
      label: "CPU · Multi-Core · Measured",
      title: "Cinebench 2024",
      score: "623 pts",
      delta: "Обганяє i3-13100, i5-11400, R5 3600X",
      percent: 0.62,
      real: true,
    },
    {
      label: "Storage SSD #1 · SEQ1M Q8T1",
      title: "CrystalDiskMark 9",
      score: "3394 / 1988",
      scoreUnit: "MB/s R/W",
      delta: "Samsung PM981 · PCIe 3.0 · виміряно",
      percent: 0.92,
      real: true,
    },
    {
      label: "Storage SSD #1 · RND4K Q32T1",
      title: "CrystalDiskMark 9",
      score: "428 / 296",
      scoreUnit: "MB/s R/W",
      delta: "Random 4K · виміряно",
      percent: 0.72,
      real: true,
    },
    {
      label: "CPU Stress Test · 100% Load",
      title: "Prime95 / HWiNFO",
      score: "74.5 °C",
      delta: "77.7W · 3880 MHz boost · стабільно",
      percent: 0.58,
      real: true,
    },
    {
      label: "Gaming · Graphics · Target",
      title: "3DMark Time Spy",
      score: "~10 850",
      delta: "Top 38% RTX 5060 · очікується",
      percent: 0.81,
      real: false,
    },
    {
      label: "Storage SSD #2 · SEQ Read · Spec",
      title: "Kingston NV3 1TB",
      score: "до 6000",
      scoreUnit: "MB/s",
      delta: "PCIe 4.0 x4 · 320 TB TBW",
      percent: 0.88,
      real: false,
    },
  ],
};

window.BUILD_DATA = BUILD_DATA;
