// =============================================
// PC MAX EDITION — Build data
// =============================================

const BUILD_DATA = {
  owner: "Максим",
  edition: "Custom Build · 2026 Q2",

  parts: [
    {
      id: "case",
      cat: "Корпус",
      name: "GameMax Spark Air",
      model: "BK · Mesh + Glass",
      price: 2119,
      qty: 1,
      color: "var(--text)",
      desc: "Mid-tower з mesh-передом для максимального airflow та загартованим склом збоку — щоб RGB не лишався без глядачів.",
      specs: [
        ["Форм-фактор", "Mid-Tower ATX"],
        ["Передня панель", "Mesh"],
        ["Бокова панель", "Tempered Glass"],
        ["Підтримка", "ATX / mATX / ITX"],
      ],
      icon: "case",
      photos: [
        "images/case/01.png", "images/case/02.png", "images/case/03.png",
        "images/case/04.png", "images/case/05.png", "images/case/06.png",
        "images/case/07.png", "images/case/08.png", "images/case/09.png",
        "images/case/10.png"
      ],
    },
    {
      id: "cpu",
      cat: "Процесор",
      name: "AMD Ryzen 5 5600",
      model: "Zen 3 · 6C/12T · sAM4",
      price: 5999,
      qty: 1,
      color: "var(--red)",
      desc: "6 ядер / 12 потоків Zen 3 — золота середина для 1080p гейму. Тримає високий FPS у CS2 і впевнено годує RTX 4060.",
      specs: [
        ["Ядра / Потоки", "6 / 12"],
        ["Базова частота", "3.5 GHz"],
        ["Boost", "до 4.4 GHz"],
        ["L3 Cache", "32 MB"],
        ["TDP", "65W"],
      ],
      icon: "cpu",
      photos: ["images/cpu/01.png", "images/cpu/02.png"],
    },
    {
      id: "mobo",
      cat: "Материнська плата",
      name: "Gigabyte B550M Aorus Elite",
      model: "sAM4 · mATX · B550",
      price: 4499,
      qty: 1,
      color: "var(--green)",
      desc: "Надійна mATX-плата з PCIe 4.0, DDR4 до 4733 MHz та двома M.2-слотами. Підходить ідеально під 5600 + потенційний апгрейд.",
      specs: [
        ["Сокет", "AM4"],
        ["Чіпсет", "AMD B550"],
        ["Форм-фактор", "mATX"],
        ["RAM", "до 128 GB DDR4-4733"],
        ["M.2 / PCIe", "2× M.2 · PCIe 4.0 x16"],
      ],
      icon: "mobo",
      photos: [
        "images/mobo/01.png", "images/mobo/02.png", "images/mobo/03.png",
        "images/mobo/04.png", "images/mobo/05.png"
      ],
    },
    {
      id: "gpu",
      cat: "Відеокарта",
      name: "ASUS Dual RTX 4060",
      model: "8 GB GDDR6 · TBD",
      price: 14999,
      qty: 1,
      color: "var(--red)",
      desc: "RTX 4060 в компактному ASUS Dual виконанні — DLSS 3, Frame Generation і повний ray tracing. Заточена під 1080p ultra без компромісів.",
      placeholder: true,
      specs: [
        ["GPU", "NVIDIA RTX 4060"],
        ["VRAM", "8 GB GDDR6"],
        ["Interface", "PCIe 4.0 x8"],
        ["DLSS", "3.0 + Frame Gen"],
        ["TDP", "115W"],
      ],
      icon: "gpu",
    },
    {
      id: "ram",
      cat: "Оперативна пам'ять",
      name: "Kingston FURY Beast",
      model: "32 GB · DDR4-3200 · 2×16",
      price: 6700,
      qty: 1,
      color: "var(--cyan)",
      desc: "32 ГБ DDR4-3200 у двоканалі — більше ніж достатньо для будь-якої сучасної гри + важких вкладок Chrome у фоні.",
      specs: [
        ["Об'єм", "32 GB (2×16 GB)"],
        ["Тип", "DDR4"],
        ["Частота", "3200 MHz"],
        ["Тайминги", "CL16"],
        ["XMP", "✓ Profile 2.0"],
      ],
      icon: "ram",
      photos: [
        "images/ram/01.png", "images/ram/02.png",
        "images/ram/03.png", "images/ram/04.png"
      ],
    },
    {
      id: "ssd1",
      cat: "SSD #1 — система",
      name: "Samsung PM981",
      model: "512 GB · NVMe M.2",
      price: 2700,
      qty: 1,
      color: "var(--violet)",
      desc: "Швидкий NVMe під систему та основні програми. Boot за 8 секунд, гра запускається ще до того, як встигнеш узяти миш.",
      specs: [
        ["Об'єм", "512 GB"],
        ["Інтерфейс", "PCIe 3.0 x4"],
        ["Форм-фактор", "M.2 2280"],
        ["Read", "до 3500 MB/s"],
        ["Write", "до 2300 MB/s"],
      ],
      icon: "ssd",
      photos: ["images/ssd1/01.png"],
    },
    {
      id: "ssd2",
      cat: "SSD #2 — ігри",
      name: "Kingston NV3 1TB",
      model: "M.2 NVMe · PCIe 4.0 x4",
      price: 3300,
      qty: 1,
      color: "var(--violet)",
      desc: "Терабайт PCIe 4.0 NVMe під ігрову бібліотеку. Cyberpunk, GOW, Forza — нехай ставляться всі одразу і завантажуються за секунди.",
      specs: [
        ["Об'єм", "1 TB"],
        ["Інтерфейс", "PCIe 4.0 x4 NVMe"],
        ["Форм-фактор", "M.2 2280"],
        ["NAND", "3D NAND"],
        ["Модель", "SNV3S/1000G"],
      ],
      icon: "ssd",
      photos: [
        "images/ssd2/01.png", "images/ssd2/02.png",
        "images/ssd2/03.png", "images/ssd2/04.png"
      ],
    },
    {
      id: "cooler",
      cat: "Кулер CPU",
      name: "ID-COOLING Frozn A410",
      model: "DK Black · Tower",
      price: 1099,
      qty: 1,
      color: "#d6d6e0",
      desc: "Tower-кулер з 4 тепловими трубками — тримає Ryzen 5 5600 холодним і тихим навіть на повному навантаженні.",
      specs: [
        ["Тип", "Tower air"],
        ["Heatpipes", "4 × 6 mm"],
        ["Сумісність", "AM4 / AM5 / LGA1700"],
        ["TDP", "до 180W"],
        ["Колір", "Чорний"],
      ],
      icon: "cooler",
      photos: [
        "images/cooler/01.png", "images/cooler/02.png", "images/cooler/03.png",
        "images/cooler/04.png", "images/cooler/05.png", "images/cooler/06.png"
      ],
    },
    {
      id: "psu",
      cat: "Блок живлення",
      name: "MSI MAG A550BN",
      model: "550W · 80+ Bronze",
      price: 2599,
      qty: 1,
      color: "var(--amber)",
      desc: "550 ват сертифікації 80+ Bronze — стабільне живлення для RTX 4060 + Ryzen 5 з запасом.",
      specs: [
        ["Потужність", "550W"],
        ["Сертифікація", "80+ Bronze"],
        ["Модульність", "Non-modular"],
        ["Вентилятор", "120 mm"],
      ],
      icon: "psu",
      photos: [
        "images/psu/01.png", "images/psu/02.png", "images/psu/03.png",
        "images/psu/04.png", "images/psu/05.png", "images/psu/06.png",
        "images/psu/07.png", "images/psu/08.png"
      ],
    },
    {
      id: "fans",
      cat: "Вентилятори",
      name: "Arctic F12 PWM PST",
      model: "120 mm · ×2",
      price: 558,
      qty: 2,
      unitPrice: 279,
      color: "var(--cyan)",
      desc: "Тихі 120мм PWM-вертушки з PST для airflow всередині корпусу. Без RGB-фарсу — просто роблять свою роботу.",
      specs: [
        ["Розмір", "120 mm"],
        ["RPM", "230-1350 PWM"],
        ["Підшипник", "Fluid Dynamic"],
        ["Шум", "до 22.5 dBA"],
        ["Кількість", "2 шт."],
      ],
      icon: "fan",
      photos: [
        "images/fan/01.png", "images/fan/02.png", "images/fan/03.png"
      ],
    },
    {
      id: "tim",
      cat: "Термоінтерфейс",
      name: "Honeywell PTM7950",
      model: "Phase-change · 8.5 W/mK",
      price: 345,
      qty: 1,
      color: "var(--violet)",
      desc: "PTM7950 — термопрокладка з фазовим переходом, що рве звичайну пасту. Поставив один раз і забув.",
      specs: [
        ["Теплопровідність", "8.5 W/mK"],
        ["Розмір", "40×40×0.2 мм"],
        ["Тип", "Phase-change"],
        ["Термін служби", "~10 років"],
      ],
      icon: "tim",
      photos: ["images/tim/01.png"],
    },
  ],

  // FPS in 1080p, realistic numbers for RTX 4060 + R5 5600
  fps: [
    { name: "Counter-Strike 2", preset: "Very High · 1080p", avg: 320, lo: 220, cyan: true },
    { name: "Cyberpunk 2077", preset: "High + DLSS Quality · 1080p", avg: 95, lo: 78 },
    { name: "GTA V", preset: "Very High · 1080p", avg: 165, lo: 130 },
    { name: "God of War", preset: "Ultra + DLSS · 1080p", avg: 110, lo: 88 },
    { name: "Forza Horizon 5", preset: "Ultra · 1080p", avg: 130, lo: 102, note: "Forza Horizon 6 — TBD" },
    { name: "Need for Speed Unbound", preset: "Ultra · 1080p", avg: 142, lo: 110 },
  ],

  benchmarks: [
    {
      label: "CPU · Multi-core",
      title: "Cinebench R23",
      score: "11 240",
      delta: "+18% vs i5-12400",
      percent: 0.74,
    },
    {
      label: "CPU · Single-core",
      title: "Cinebench R23",
      score: "1 558",
      delta: "+5% vs 5500",
      percent: 0.62,
    },
    {
      label: "Gaming · Graphics",
      title: "3DMark Time Spy",
      score: "10 850",
      delta: "Top 38% RTX 4060",
      percent: 0.81,
    },
    {
      label: "Storage · Sequential",
      title: "CrystalDiskMark",
      score: "3 480 MB/s",
      delta: "PCIe 3.0 NVMe",
      percent: 0.92,
    },
  ],

  timeline: [
    {
      step: "01",
      title: "Замовлення комплектуючих",
      desc: "Усі деталі замовлено та зібрано в одному місці. Чекаємо доставку відеокарти.",
      status: "done",
      tag: "Виконано",
    },
    {
      step: "02",
      title: "Підготовка робочого місця",
      desc: "Антистатичний браслет, викрутки, термопрокладка під рукою. Стіл прибрано.",
      status: "done",
      tag: "Виконано",
    },
    {
      step: "03",
      title: "Монтаж процесора + RAM",
      desc: "Встановлення Ryzen 5 5600 у сокет AM4, фіксація захисної рамки, інсталяція 32 ГБ Kingston Fury у слоти A2/B2.",
      status: "now",
      tag: "В процесі",
    },
    {
      step: "04",
      title: "Установка кулера + PTM7950",
      desc: "Накладання Honeywell PTM7950, монтаж ID-COOLING Frozn A410 з контактним пресуванням.",
      status: "next",
      tag: "Далі",
    },
    {
      step: "05",
      title: "Установка плати в корпус",
      desc: "Кріплення Gigabyte B550M Aorus Elite на стійки корпусу, підключення передньої панелі та I/O.",
      status: "next",
      tag: "Далі",
    },
    {
      step: "06",
      title: "Блок живлення + кабель-менеджмент",
      desc: "Монтаж MSI A550BN, прокладання кабелів за піддоном, фіксація стяжками. Без хаосу.",
      status: "next",
      tag: "Далі",
    },
    {
      step: "07",
      title: "Встановлення SSD + GPU",
      desc: "M.2 Samsung PM981 у слот #1, Kingston 1TB поруч, RTX 4060 у PCIe x16 + підключення 8-pin.",
      status: "next",
      tag: "Далі",
    },
    {
      step: "08",
      title: "Перший запуск + Windows",
      desc: "POST, оновлення BIOS, установка Windows 11, драйверів, Steam, Discord — готова станція.",
      status: "next",
      tag: "Далі",
    },
    {
      step: "09",
      title: "Подарунок Максиму 🎁",
      desc: "Сюрприз. Реакція. Можливо, сльози (твої, не його).",
      status: "next",
      tag: "Кінцева мета",
    },
  ],
};

window.BUILD_DATA = BUILD_DATA;
